# Generated by Django 4.2.13 on 2024-07-31 01:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('job_title', models.CharField(help_text='this hold the Job title of the current job', max_length=250, null=True, verbose_name='Job Title')),
                ('fee', models.DecimalField(decimal_places=2, help_text='this hold the fee', max_digits=20, null=True, verbose_name='Enrollment Fee')),
                ('description', models.TextField(help_text='this hold the Job Description of the current job post ', verbose_name='Job Description')),
            ],
            options={
                'verbose_name': 'Job Portal',
                'verbose_name_plural': 'Job Portal',
                'ordering': ['-created_date'],
            },
        ),
    ]
