# Generated by Django 4.2.13 on 2024-07-31 02:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_jobenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='this hold the amount paid', max_digits=20, null=True, verbose_name='Amount Paid')),
                ('payment_ref', models.CharField(help_text='this hold the Transaction Ref for the current transaction ', max_length=100, null=True, verbose_name='Transaction Ref')),
                ('voter_name', models.CharField(help_text='this hold the Voter name of the contestant ', max_length=100, null=True, verbose_name='Voter Name')),
                ('settled', models.BooleanField(default=False, null=True, verbose_name='Payment Settled')),
                ('status', models.CharField(help_text='this hold the Voter name of the contestant ', max_length=100, null=True, verbose_name='Status')),
                ('job_aplicant', models.ForeignKey(help_text='this hold the aplicant details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobenrollment', verbose_name='Job Aplicant')),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_date'],
            },
        ),
    ]
