# Generated by Django 4.2.13 on 2024-08-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobenrollment',
            name='date_of_birth',
            field=models.DateField(max_length=25, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='job_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobportal', verbose_name='Job Categories'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='local_gov_area',
            field=models.CharField(max_length=100, null=True, verbose_name='Local Gov Area'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='means_of_identification',
            field=models.CharField(max_length=40, null=True, verbose_name='Means Of Identification'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='names',
            field=models.CharField(max_length=250, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='next_of_kin',
            field=models.CharField(max_length=100, null=True, verbose_name='Name Of Next Of Kin'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='place_of_birth',
            field=models.CharField(max_length=250, null=True, verbose_name='Place Of Birth'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='referee',
            field=models.CharField(max_length=100, null=True, verbose_name='Name Of Referee and Phone Number'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='residential_address',
            field=models.CharField(max_length=350, null=True, verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='state_of_origin',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'Federal Capital Territory'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=40, null=True, verbose_name='State Of Origin'),
        ),
        migrations.AlterField(
            model_name='jobenrollment',
            name='state_of_residential',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'Federal Capital Territory'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=40, null=True, verbose_name='State Of Residential'),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_title',
            field=models.CharField(max_length=250, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_ref',
            field=models.CharField(help_text='this hold the Transaction Ref for the current transaction', max_length=100, null=True, verbose_name='Transaction Ref'),
        ),
    ]
