# Generated by Django 4.2.13 on 2024-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobenrollment_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobenrollment',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Job Title'),
        ),
    ]
