# Generated by Django 4.2.13 on 2024-08-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_jobenrollment_completed_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobenrollment',
            name='referee',
            field=models.CharField(max_length=100, null=True, verbose_name='Name Of Referee'),
        ),
    ]
